#!/bin/bash

function installation
{
    if [ ! -d ~/.jvc ]; then
        mkdir ~/.jvc
        touch ~/.jvc/topics.xml
    fi
}

installation
case $1 in 
    linux) url=38;;
    15-18) url=http://ws.jeuxvideo.com/forums/0-50-0-1-0-1-0-0.xml;;
    commu) url=http://ws.jeuxvideo.com/forums/0-1000021-0-1-0-1-0-0.xml;;
    creajeux) url=http://ws.jeuxvideo.com/forums/0-31-0-1-0-1-0-0.xml;;
    creaweb) url=http://ws.jeuxvideo.com/forums/0-30-0-1-0-1-0-0.xml;;
esac

curl -s -u app_and_gnw:FC?4554? http://ws.jeuxvideo.com/forums/0-$url-0-1-0-1-0-0.xml > ~/.jvc/topics.xml
if [ -z $2 ]; then
    xmlstarlet sel -t -v  "//topic/titre/text()" ~/.jvc/topics.xml && echo -e "\n"

elif [ $2 == "author" ]; then
    curl -s -u app_and_gnw:FC?4554? http://ws.jeuxvideo.com/forums/0-$url-0-1-0-1-1-$(echo $3 | tr '[[:upper:]]' '[[:lower:]]').xml > ~/.jvc/search.xml
    xmlstarlet sel -t -v "//topic/titre/text()" ~/.jvc/search.xml && echo -e "\n"

elif [ $2 == "topic" ]; then
    postNumber=`xmlstarlet sel -t -v "//topic[titre=\"$3\"]/nb_reponses/text()" ~/.jvc/topics.xml`
    pageNumber=$(( $postNumber / 20 + 1))
    urltopic=`xmlstarlet sel -t -v "//topic[titre=\"$3\"]/lien_topic/text()" ~/.jvc/topics.xml`
    urltopic=${urltopic#jv:\/\/}
    urltopic=${urltopic%-1-0-1-0-0.xml}
    echo $urltopic
    curl -s -u app_and_gnw:FC?4554? http://ws.jeuxvideo.com/$urltopic-$pageNumber-0-1-0-0.xml > ~/.jvc/posts.xml
    xmlstarlet sel -t -v "//li[@class=\"post\"]/p/text()" ~/.jvc/posts.xml | sed s/"&lt;"/"<"/g | sed s/"&gt;"/">"/g


elif [ $2 == "search" ]; then
    curl -s -u app_and_gnw:FC?4554? http://ws.jeuxvideo.com/forums/0-$url-0-1-0-1-2-$(echo $3 | tr '[[:upper:]]' '[[:lower:]]').xml > ~/.jvc/search.xml
    xmlstarlet sel -t -v "//topic/titre|auteur/text()" ~/.jvc/search.xml && echo -e "\n"
fi
